products:
    label: Categories Line Product
    view:
        list: $/radit/catalog/models/product/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/radit/catalog/models/product/fields.yaml
        recordsPerPage: 10